### ISSUE TITLE
Dockerfile outdated

### ISSUE THREAD

**Issue by haemka** [mwtek/dashboarddataprocessor#10]
Zusätzlich zu #9 möchte ich darauf hinweisen, dass das aktuell im Repo vorhandene Dockerfile nicht mehr aktuell (Versionsnummer des JAR veraltet) ist und die Pfade darin von vornherein nicht stimmen. Außerdem wird hier noch das deprecated `openjdk:17`-Image verwendet.

Ein funktionierendes Dockerfile für ein In-Place build mit einem JDK-Image mit Support direkt im Repository wäre:
```
FROM eclipse-temurin:17-alpine AS dashboard-data-processor
COPY target/dashboarddataprocessor-*.jar /dashboarddataprocessor/dashboard-data-processor.jar
COPY src/main/resources/application.yaml /dashboarddataprocessor
RUN ["java","-jar","/dashboarddataprocessor/dashboard-data-processor.jar","--spring.config.location=/dashboarddataprocessor/application.yaml"]
```

Ich habe hier das [Temurin](https://hub.docker.com/_/eclipse-temurin)-Image verwendet, da es problemlos die Integration eigener CAs erlaubt. Außerdem ein Alpine-Image, da es 100MB kleiner als das reguläre ist.
Statt `ENTRYPOINT` wird hier `RUN` verwendet, da so der Befehl als Parameter an den eigentlichen `ENTRYPOINT` angehängt wird. Beim Temurin-Image ist das das Zertifikatsupdateskript. Der übergebene Parameter wird dann nach dem Update der Zertifikate ausgeführt.

**Comment by Tim-Steinbach-UKB** [comment]
Das Update des Dockerfile ist bereits mit dem letzten Release auf 0.5.0-alpha1 erfolgt.
Auch wurde das Image des JDK ausgetauscht. Wir hatten uns allerdings für eins von amazon entschieden.
Gerne vergleichen wir das nochmal mit dem von Temurin

**Comment by haemka** [comment]
[Das hier](https://github.com/mwtek/dashboarddataprocessor/blob/main/Dockerfile) wurde scheinbar nicht ausgetauscht.

Und bei [dem hier](https://github.com/mwtek/dashboarddataprocessor/blob/main/docker-image/Dockerfile) stimmen die Pfade auch nicht (application.yaml liegt nicht im /dashboarddataprocessor). Zudem stimmt keiner der Pfade sobald man es direkt aus dem Verzeichnis in dem es liegt ausführt. Theoretisch muss es von außerhalb des Repositories mit dem Relativpfad-Aufruf `docker build ./dashboarddataprocessor/docker-image/Dockerfile` aufgerufen werden. Oder per Skrip mit dem Relativpfad `./dashboarddataprocessor/docker-image/build-docker.sh`. Wobei das Skript noch ganz andere Probleme mit sich bringt, da der ganze "Check group" block stark OS-spezifisch ist. Außerdem kapselt es nur Standardfunktionen von Docker, welche vielleicht besser als Anleitung  im README aufgehoben wären.

**Comment by Tim-Steinbach-UKB** [comment]
Das ist im Hauptverzeichnis anscheinend nicht gelöscht worden. Das befindet sich jetzt hier:
https://github.com/mwtek/dashboarddataprocessor/blob/main/docker-image/Dockerfile

Pfade werde ich nocheinmal prüfen.

**Comment by Tim-Steinbach-UKB** [comment]
Angepasst in Version [V0.5.0-alpha2](https://github.com/mwtek/dashboarddataprocessor/releases/tag/v0.5.0-alpha2)
