### ISSUE TITLE
neue codes für Beatmung

### ISSUE THREAD

**Issue by KutSaleh** [mwtek/dashboarddataprocessor#11]
Es sind nun zwei neuen Codes für die Beatmung (procedure.code) im Modul ICU veröffentlich siehe [ValueSet](https://simplifier.net/medizininformatikinitiative-modul-intensivmedizin/vs-mii-icu-code-procedure-beatmung-snomed). Wäre es möglich, diese beide Codes im DDP zu berücksichtigen, falls nur bestimmten Codes aus dem o. g. ValueSet als Filter im DDP verwenden werden.

**Comment by dmeyers138** [comment]
Hey @KutSaleh ,
danke für die Info!
Die neuen Codes sollten in der `application.yaml` unter `global.inputcodes.procedure.ventilation` ergänzt werden können. 
Bitte mal gegentesten – die Default-Liste wird mit dem nächsten Update aktualisiert.

**Comment by dmeyers138** [comment]
Codes wurden im neuen Release mitaufgenommen.
