### ISSUE TITLE
No encounter with an identifier.slice 'Aufnahmenummer' was found.

### ISSUE THREAD

**Issue by ericukj** [mwtek/dashboarddataprocessor#12]
Beim Aufrufen des createJson Endpunkt bekommen wir nach einiger Zeit den Fehler 

`No encounter with an identifier.slice 'Aufnahmenummer' was found.`

Auf dem FHIR Server sind eine große Anzahl von Encounter-Ressourcen gespeichert die alle dem Profil des MII - Basismodul Fall (2024) entsprechen und auch das Slice 'Aufnahmenummer' bedienen. Die Ressourcen haben in unserem Fall beispielhaft folgenden Aufbau:

```{
{
    "resourceType": "Encounter",
    "id": "12345",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2024-05-23T00:01:01.0001+02:00",
        "source": "http://www.uniklinikum-jena.de/fhir/origin/orchestra/adt",
        "profile": [
            "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung"
        ],
        "tag": [
            {
                "system": "http://www.uniklinikum-jena.de/fhir/tag",
                "code": "ADT-Mapping-1.1.0"
            }
        ]
    },
    "identifier": [
        {
            "use": "secondary",
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "VN",
                        "display": "Visit number"
                    }
                ]
            },
            "system": "http://www.uniklinikum-jena.de/fhir/sid/encounter",
            "value": "012345678"
        },
        {
            "use": "secondary",
            "system": "http://www.uniklinikum-jena.de/fhir/sid/bewegungsnummer",
            "value": "00001"
        },
        {
            "use": "official",
            "system": "http://www.uniklinikum-jena.de/fhir/sid/hl7id",
            "value": "54321"
        }
    ],
    "status": "finished",
    "class": {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code": "AMB",
        "display": "ambulatory"
    },
    "type": [
        {
            "coding": [
                {
                    "system": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Kontaktebene",
                    "code": "einrichtungskontakt",
                    "display": "Einrichtungskontakt"
                }
            ]
        }
    ],
    "subject": {
        "reference": "Patient/123456789"
    },
    "period": {
        "start": "2024-01-01T01:01:00+02:00"
    },
    "serviceProvider": {
        "reference": "Organization/123",
        "display": "Universitätsklinikum Jena"
    }
}

**Comment by dmeyers138** [comment]
Hey @ericukj 

danke für das Feedback!
Das Encounter-Beispiel sieht gut aus, da scheint auf dne ersten Blick alles in Ordnung zu sein.
Die Logik, welche die Aufnahmenummer prüft und verwaltet befindet sich in Zeile 190 in 
```
DashboardLogic.DiseaseResultFunctionality.generateSupplyContactToFacilityContactMap
```
und macht nichts anderes als über die Versorgungsstellenkontakte zu iterieren und diesen den dazugehörigen Einrichtungskontakt zuzuweisen. 

Haben die Versorgungsstellenkontakte bei euch im ```Encounter.identifier``` einen analogen Aufbau wie dein Einrichtungskontakt-Beispiel?

Interessehalber: Kannst du testweise mal bitte in der ```application.yaml``` in Zeile 13 das ```use-part-of-instead-of-identifier``` auf ```true``` setzen (falls ihr in den Encounter-Ressourcen der unteren Hierarchie-Ebenen das ```.partOf``` gesetzt habt) und Rückmeldung geben, ob ihr damit einen Output bekommt?

**Comment by ericukj** [comment]
Unsere `Encounter.identifier` sind auf jeder Ebene ähnlich aufgebaut. Die Ressourcen enthalten meist hausinterne identifer und die nötigen Informationen aus dem Profil,
Wenn ich den Parameter `use-part-of-instead-of-identifier` auf true setze bekomme ich trotzdem einen ähnlichen Fehler. In der Debug-Konsole sind dann folgende Meldungen zu finden:
```
INFO 25916 --- [nio-9091-exec-2] d.u.m.d.l.DiseaseResultFunctionality     : No usable Encounter.identifier references found -> trying to get these info via Encounter.partOf additionally
ERROR 25916 --- [nio-9091-exec-2] d.u.m.dashboard.DashboardApplication     : Workflow aborted: No encounter with an identifier.slice 'Aufnahmenummer' was found. 
```
Bei uns wird auch das `Encounter.partOf` Attribut verwendet, um die Beziehung zwischen den Ressourcen abzubilden. Interessant ist noch, der Error entsteht bereits 1ms nach der INFO. Es werden also scheinbar keine bis wenige Encounter geprüft. Gibt es evtl. eine weitere Einschränkung der Encounter, welche bereits alle filtert und dann verwirft?

**Comment by dmeyers138** [comment]
Ich habe eine Vermutung:
Bei der Ermittlung der Einrichtungskontakte wird ```Encounter.type.coding.system``` geprüft.
Erwartet wird ```"http://fhir.de/CodeSystem/Kontaktebene"```, in deinem Beispiel ist das Feld jedoch mit ```https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Kontaktebene``` besetzt. 

Hat das einen besonderen Grund ? 
Laut aktuellem [IG](https://simplifier.net/guide/mii-ig-modul-fall-2024-de/MIIIGModulFall/TechnischeImplementierung/FHIRProfile/EncounterKontaktGesundheitseinrichtung.page.md?version=current) müsste die erstere URL dem [Binding zum Codesystem](https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656793/~table) entsprechen?

**Comment by ericukj** [comment]
Das wird höchstwahrscheinlich der Fehler sein. Ich glaube das Codes-System was hier verwendet wurde, stammt noch aus einer älteren Version des Profils und wurde in den Ressourcen noch nicht aktualisiert.

**Comment by KutSaleh** [comment]
> Ich habe eine Vermutung: Bei der Ermittlung der Einrichtungskontakte wird `Encounter.type.coding.system` geprüft. Erwartet wird `http://fhir.de/CodeSystem/Kontaktebene`, in deinem Beispiel ist das Feld jedoch mit `https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Kontaktebene` besetzt.
> 
> Hat das einen besonderen Grund ? Laut aktuellem [IG](https://simplifier.net/guide/mii-ig-modul-fall-2024-de/MIIIGModulFall/TechnischeImplementierung/FHIRProfile/EncounterKontaktGesundheitseinrichtung.page.md?version=current) müsste die erstere URL dem [Binding zum Codesystem](https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656793/~table) entsprechen?

könnte die Prüfung nach dem Encounter.type.coding.system *zunächst* deaktiviert werden? wichtig ist ja das Code an sich.

**Comment by dmeyers138** [comment]
> > Ich habe eine Vermutung: Bei der Ermittlung der Einrichtungskontakte wird `Encounter.type.coding.system` geprüft. Erwartet wird `http://fhir.de/CodeSystem/Kontaktebene`, in deinem Beispiel ist das Feld jedoch mit `https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Kontaktebene` besetzt.
> > Hat das einen besonderen Grund ? Laut aktuellem [IG](https://simplifier.net/guide/mii-ig-modul-fall-2024-de/MIIIGModulFall/TechnischeImplementierung/FHIRProfile/EncounterKontaktGesundheitseinrichtung.page.md?version=current) müsste die erstere URL dem [Binding zum Codesystem](https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656793/~table) entsprechen?
> 
> könnte die Prüfung nach dem Encounter.type.coding.system _zunächst_ deaktiviert werden? wichtig ist ja das Code an sich.

das einfachste wäre wohl, wenn ihr, bis ihr die Daten nachgezogen habt, die URL im Code temporär selbst anpasst und neu kompiliert:
siehe Utilities-Package -> ```de.ukbonn.mwtek.utilities.enums.EncounterContactLevel.SYSTEM``` (Zeile 36)

Wäre das eine akzeptable Übergangslösung? 

Zukünftig werde ich das Logging hier erweitern und Mechanismen einbauen, die bereits warnen, wenn keine verwertbaren Einrichtungskontakt-Encounter gefunden werden konnten, danke also nochmal für das Feedback :-)

**Comment by FloSeidel** [comment]
Hi @dmeyers138 
ich habe im Prinzip die gleiche Fehlermeldung. Allerdings beruht diese scheinbar auf einem anderen Problem. Soweit ich das überblicke, ist der Typ der Aufnahmenummer korrekt gesetzt. auch der Typ des Encounters selbst scheint mir korrekt gesetzt zu sein. Ich könnte mir aber vorstellen, dass der DDP aktuell noch ein Problem damit hat, dass wir ausschließlich Einrichtungskontakte im Bestand haben. Ich hätte aber erwartet, dass es Datenpunkte gibt, die auch ohne Abteilungs- / Versorgungsstellenkontakte auskommen? - Oder liege ich da falsch?

**Comment by dmeyers138** [comment]
> Hi @dmeyers138 ich habe im Prinzip die gleiche Fehlermeldung. Allerdings beruht diese scheinbar auf einem anderen Problem. Soweit ich das überblicke, ist der Typ der Aufnahmenummer korrekt gesetzt. auch der Typ des Encounters selbst scheint mir korrekt gesetzt zu sein. Ich könnte mir aber vorstellen, dass der DDP aktuell noch ein Problem damit hat, dass wir ausschließlich Einrichtungskontakte im Bestand haben. Ich hätte aber erwartet, dass es Datenpunkte gibt, die auch ohne Abteilungs- / Versorgungsstellenkontakte auskommen? - Oder liege ich da falsch?

Hey @FloSeidel 
es gibt einige Datenitems die ohne AK/VK-Ressourcen auskommen, korrekt. 
Auch, die Fehlerursache hast du korrekt erkannt, die aktuelle DDP Version erwartet nämlich bei stationären Encountern, dass auch AK/VK-Exemplare existieren – das verlangt der KDS Fall IG nun mal :-)
Intern existiert allerdings schon länger ein Feature Request, bei Nicht-Existenz von AK/VKs nur die Items auszugeben, die hiervon unbetroffen sind.
Da bisher kein Standort über ein Verlangen nach einem solchen Feature geäußert habe, lag das aber erstmal auf Eis. 
Gehe ich gerne sehr zeitnah an, allerdings kann ich nicht versprechen, dass ausschließlich via EK-Ressourcen ein Meilenstein-Threshold (25%/50% etc. der zu liefernden Items) erreicht werden kann. Alles Items, die mit icu/(max)treatmentlevel zu tun haben sind nämlich dann nicht valide generierbar.
