### ISSUE TITLE
No encounter with an identifier.slice 'Aufnahmenummer' was found. (die Zweite ;))

### ISSUE THREAD

**Issue by FloSeidel** [mwtek/dashboarddataprocessor#13]
Hi @dmeyers138,
ich habe im Prinzip die gleiche Fehlermeldung, wie in diesem Issue https://github.com/mwtek/dashboarddataprocessor/issues/12. 

Allerdings beruht diese scheinbar auf einem anderen Problem. Soweit ich das überblicke, ist der Typ der Aufnahmenummer korrekt gesetzt. auch der Typ des Encounters selbst scheint mir korrekt gesetzt zu sein. Ich könnte mir aber vorstellen, dass der DDP aktuell noch ein Problem damit hat, dass wir ausschließlich Einrichtungskontakte im Bestand haben. Ich hätte aber erwartet, dass es Datenpunkte gibt, die auch ohne Abteilungs- / Versorgungsstellenkontakte auskommen? - Oder liege ich da falsch?

**Comment by ericukj** [comment]
Ich muss mich dazu auch noch einmal einschalten. 
Wir haben nun korrekte Code-Systeme für jede Ebene von Encountern. Auch wenn bis jetzt nur relativ kleine Menge den korrekten Ressourcen entsprechen, bekommen wir wieder den oben genannten Fehler. Wenn ich in unserem FHIR-Server nun eine Search-Anfrage mit folgender URL stelle bekomme ich auch alle korrekten Encounter Ressourcen:
`https://my-fhir-server.de/fhir/Encounter?type=http://fhir.de/CodeSystem/Kontaktebene|`
Dabei ist wichtig, dass am Ende ein Pipe-Symbol angefügt wird, damit alle Codes dieses Systems gefunden werden können.

**Comment by dmeyers138** [comment]
> Hi @dmeyers138, ich habe im Prinzip die gleiche Fehlermeldung, wie in diesem Issue #12.
> 
> Allerdings beruht diese scheinbar auf einem anderen Problem. Soweit ich das überblicke, ist der Typ der Aufnahmenummer korrekt gesetzt. auch der Typ des Encounters selbst scheint mir korrekt gesetzt zu sein. Ich könnte mir aber vorstellen, dass der DDP aktuell noch ein Problem damit hat, dass wir ausschließlich Einrichtungskontakte im Bestand haben. Ich hätte aber erwartet, dass es Datenpunkte gibt, die auch ohne Abteilungs- / Versorgungsstellenkontakte auskommen? - Oder liege ich da falsch?

Hey @FloSeidel 
es gibt einige Datenitems die ohne AK/VK-Ressourcen auskommen, korrekt.
Auch, die Fehlerursache hast du korrekt erkannt, die aktuelle DDP Version erwartet nämlich bei stationären Encountern, dass auch AK/VK-Exemplare existieren – das verlangt der KDS Fall IG nun mal :-)
Intern existiert allerdings schon länger ein Feature Request, bei Nicht-Existenz von AK/VKs nur die Items auszugeben, die hiervon unbetroffen sind.
Da bisher kein Standort über ein Verlangen nach einem solchen Feature geäußert habe, lag das aber erstmal auf Eis.
Gehe ich gerne sehr zeitnah an, allerdings kann ich nicht versprechen, dass ausschließlich via EK-Ressourcen ein Meilenstein-Threshold (25%/50% etc. der zu liefernden Items) erreicht werden kann. Alles Items, die mit icu/(max)treatmentlevel zu tun haben sind nämlich dann nicht valide generierbar.

**Comment by FloSeidel** [comment]
> > Hi @dmeyers138, ich habe im Prinzip die gleiche Fehlermeldung, wie in diesem Issue #12.
> > Allerdings beruht diese scheinbar auf einem anderen Problem. Soweit ich das überblicke, ist der Typ der Aufnahmenummer korrekt gesetzt. auch der Typ des Encounters selbst scheint mir korrekt gesetzt zu sein. Ich könnte mir aber vorstellen, dass der DDP aktuell noch ein Problem damit hat, dass wir ausschließlich Einrichtungskontakte im Bestand haben. Ich hätte aber erwartet, dass es Datenpunkte gibt, die auch ohne Abteilungs- / Versorgungsstellenkontakte auskommen? - Oder liege ich da falsch?
> 
> Hey @FloSeidel es gibt einige Datenitems die ohne AK/VK-Ressourcen auskommen, korrekt. Auch, die Fehlerursache hast du korrekt erkannt, die aktuelle DDP Version erwartet nämlich bei stationären Encountern, dass auch AK/VK-Exemplare existieren – das verlangt der KDS Fall IG nun mal :-) Intern existiert allerdings schon länger ein Feature Request, bei Nicht-Existenz von AK/VKs nur die Items auszugeben, die hiervon unbetroffen sind. Da bisher kein Standort über ein Verlangen nach einem solchen Feature geäußert habe, lag das aber erstmal auf Eis. Gehe ich gerne sehr zeitnah an, allerdings kann ich nicht versprechen, dass ausschließlich via EK-Ressourcen ein Meilenstein-Threshold (25%/50% etc. der zu liefernden Items) erreicht werden kann. Alles Items, die mit icu/(max)treatmentlevel zu tun haben sind nämlich dann nicht valide generierbar.

Danke für die Info! Ja das klingt gut. Wir sind ohne hin drann die Umsetzung des Fall Moduls zu verbessern, dennoch fänd ich die Umsetzung ganz schön, dass zumindest das berechnet wird, zu dem Informationen im FHIR Store vorliegen. :)

**Comment by dmeyers138** [comment]
Die heute veröffentlichte 0.5.3-alpha1 Version exkludiert automatisch alle Items die VK-Informationen benötigen, im Fall dass keine VK-Ressourcen gefunden werden konnten und gibt eine Warnung aus. Falls das für euch noch relevant ist, bitte gegenprüfen. :-)
